- core/types/l2trace_block.go
This is required to validate a transaction by kanvas-prover.
> feat: add Mint to TransactionTrace

- cmd/geth/main.go
- cmd/utils/flags.go
- eth/api_backend.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/handler.go
- eth/handler_eth.go
- les/client.go
This commit removes 2 flags.
- `RollupSequencerHttpFlag`: This transfers transaction to geth that is specified with this flag.
- `RollupDisableTxPoolGossipFlag`: This diables tx pool sync if this flag is on.
> feat: enable tx pool sync by force

- core/block_validator_test.go
This test is failed since [68bfa8b](https://github.com/light-scale/go-ethereum/commit/68bfa8b473bb8770216517f007b521fab41c5afa), which is introduced by Optimism. 
To introduce CI testing, we decided to skip this test for the time being. 
Once we know the reason why this is failed, then we need to re-enable this test.
> ci: disable unittest temporarily for CI introduction

- .github/workflows/ci.yml
- .github/workflows/test.yml
- mobile/android_test.go
Add ci pipeline and test pipeline
* test will be executed on push
* ci is the dev branch, so it only runs on merge
Our docker hub is managed by [lightscale](https://hub.docker.com/u/lightscale)
> ci: add ci pipeline and test pipeline

- accounts/abi/bind/backends/simulated.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/freezer_table_test.go
- core/state_transition.go
- core/types/receipt.go
- core/types/rollup_l1_cost.go
- core/types/rollup_l1_cost_test.go
- core/types/transaction.go
- core/types/transaction_marshalling.go
- core/types/transaction_marshalling_test.go
- eth/state_accessor.go
These are changes can be applied at this moment. We need to apply changes due to [regolith](https://github.com/ethereum-optimism/optimism/blob/develop/specs/network-upgrades.md#regolith).
> feat: apply op geth changes

- trie/zk_trie.go
Path must be computed using poseidon hash once. But, by mistake, it was computed using twice.
> fix(trie): use hash once on account to compute path

- FORK.md
- accounts/abi/bind/backends/simulated.go
- cmd/evm/internal/t8ntool/execution.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/state_processor.go
- core/state_transition.go
- core/types/deposit_tx.go
- core/types/receipt.go
- core/types/receipt_test.go
- core/types/transaction.go
- core/types/transaction_marshalling.go
- core/types/transaction_marshalling_test.go
- core/types/tx_access_list.go
- core/types/tx_dynamic_fee.go
- core/types/tx_legacy.go
- eth/api.go
- internal/ethapi/api.go
- Optimism regolith disables system tx. This means gas account logic is the same as user deposit tx.
- use depositNonce to compute contract address.
- set depositNonce as nonce in transaction receipt.
See https://github.com/ethereum-optimism/optimism/blob/develop/specs/network-upgrades.md#post-bedrock-network-upgrades
> feat: apply optimism regolith changes

- .github/workflows/ci.yml
wemixkanvas is being used as a new Docker Hub repository
> ci: change docker hub name(lightscale=>wemixkanvas)

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- Dockerfile
change the Go version used during build to 1.18 in order to use `mrand.Seed` which is deprecated since Go 1.20 and used in `trie/zk_trie_proof_test.go`
> chore: change docker builder version(1.20=>1.18)

- core/types/transaction_marshalling.go
- core/types/transaction_marshalling_test.go
While implementing https://github.com/kroma-network/kroma/issues/17,
I faced the issue that a deposit transaction is transformed to
a deposit transaction with nonce during unmarshaling from rpc transaction.
The problem is marshaling of a transaction with nonce omits some of
properties this leads to several unexpected results.
This isn't meant to be a good solution for the regarding issue above.
For example, `SourceHash()` of a deposit transaction with nonce doesn't
return what we expect as a deposit transaction does.
Still, this is a enough change for me to get public input from output
root for ZK fault proof.
> feat: enable marshaling deposit tx with nonce

- accounts/abi/bind/backends/simulated.go
- core/state_prefetcher.go
- core/state_processor.go
- core/state_transition.go
- core/types/fee_distribution.go
- core/vm/evm.go
- eth/api_backend.go
- eth/state_accessor.go
- eth/tracers/api.go
- eth/tracers/api_blocktrace.go
- eth/tracers/api_test.go
- les/api_backend.go
- les/state_accessor.go
DepositTx updates the ValidatorRewardRatio in the L1Block contract, which is used to distribute the tx fee to ProtocolVault and ValidatorRewardVault.
> feat: add fee distribution via L1Block contract

- accounts/abi/bind/backends/simulated.go
- core/evm.go
- core/state_prefetcher.go
- core/state_processor.go
- eth/api_backend.go
- eth/state_accessor.go
- eth/tracers/api.go
- eth/tracers/api_blocktrace.go
- eth/tracers/api_test.go
- les/api_backend.go
- les/odr_test.go
- les/state_accessor.go
- light/odr_test.go
- tests/state_test.go
- tests/state_test_util.go
This also fixes a segfault issue when executing json rpc `debug_traceBlockByNumber` by setting missing L1CostFunc correctly.
Related: https://github.com/ethereum-optimism/op-geth/pull/71
> refac: set {L1Cost,FeeDistribution}Func in NewEVMBlockContext

- cmd/evm/testdata/1/exp.json
- cmd/evm/testdata/13/exp2.json
- cmd/evm/testdata/23/exp.json
- cmd/evm/testdata/24/exp.json
- cmd/evm/testdata/25/exp.json
- cmd/evm/testdata/3/exp.json
- core/types/gen_receipt_json.go
- core/types/receipt.go
In the kroma e2e test, errors occurred that `EffectiveGasPrice` and `DepositNonce` could not be unmarshaled. 
In this regard, there was some discrepancy between `receipt` and `gen_receipt_json.go`. 
Referring to this [PR](https://github.com/ethereum/go-ethereum/pull/27114), which was also reflected in `ethereum/go-ethereum`, `gen_receipt_json.go` has been regenerated and testdata were modified accordingly.
And the `EffectiveGasPrice` is required as described in [spec](https://github.com/ethereum/execution-apis/blob/af82a989bead35e2325ecc49a9023df39c548756/src/schemas/receipt.yaml#L49), so the `omitempty` tag has been removed.
> fix(core): fix discrepancy in receipt

- .github/workflows/ci.yml
change the policy to differentiate commits that are merged into the dev branch by tagging them in the docker image
> ci: change dev tag name

- core/types/fee_distribution.go
Renamed 'validator reward ratio' to 'validator reward numerator' since it is improper to call a numerator as ratio.
> refac(core): rename variables

- core/types/l2trace.go
- eth/tracers/api_blocktrace.go
extend trace to support type 2 transaction
- A trace includes gas price which equals to effective price
- A trace includes access list when the tx's type is 2
> feat(core): extend trace for supporting type2 tx

- core/state_processor.go
The nonce of the deposit transaction is always +1. As a result, if the deposit transaction is a contract deployment transaction, the contract address is being generated incorrectly. As a result, the contract code cannot be retrieved from the L2.
This commit normalizes the nonce. 
The deposit nonce of the receipt and the nonce of the tx will change, but the txhash and receipt hash will be the same, so no hard fork is required.
However, the tx.nonce value will continue to differ by one from previously stored data and geths that are not receiving the patch.
I validated block, tx, and receipt from genesis to 240,000 blocks on the mainnet. I also validated running with data already in place.
Data I validated
- block.hash
- block.parentHash
- deposit tx nonce 1 difference
- receipt.depositNonce …
> fix: fixed deposit tx always incremented nonce by 1

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/blockchain.go
- core/state/database.go
- eth/backend.go
- eth/ethconfig/config.go
- trie/database.go
- trie/iterator.go
- trie/iterator_test.go
- trie/merkle_trie.go
- trie/zk/merkle_tree.go
- trie/zk/merkle_tree_node.go
- trie/zk/merkle_tree_test.go
- trie/zk/testinput_test.go
- trie/zk/tree_path.go
- trie/zk/tree_path_test.go
- trie/zk/util.go
- trie/zk_merkle_stack_trie.go
- trie/zk_merkle_state_trie.go
- trie/zk_merkle_trie.go
- trie/zk_trie.go
- trie/zk_trie_test.go
- trie/zkproof/writer.go
see https://github.com/kroma-network/go-ethereum/issues/44
A stricter implementation would be to use []byte for the key and no key hash in the tree, but i didn't do that this time.
> feat: implement zk merkle tree

- trie/iterator_test.go
- trie/triedb/hashdb/zktrie_database.go
- trie/zk_merkle_trie.go
- trie/zk_trie.go
Previously, there was a bug that prevented the chain from running because the genesis block was not found after the https://github.com/ethereum/go-ethereum/pull/26703 commit. It was solved by reversing the root hash when committing and saving it once more, but this resulted in using about 90 bytes of disk space per block and slowed down the block generation speed by about 30ms. (About 60ms -> 90m for 1 tx block, see related commit https://github.com/kroma-network/go-ethereum/commit/6f7eadcd8ff728061b418dc1e10e77fb4cd32395 )
This commit fixes the above.
> fix(trie): dont save root hash twice

- trie/zk/merkle_tree_node.go
- trie/zk/merkle_tree_test.go
- trie/zk_merkle_state_trie.go
- trie/zk_merkle_trie_test.go
This PR fixes below issues.
1. The key preimage was not being saved.
2. The key preimage format was incorrect when gettingProof.
> fix: key preimage not saved, invalid format

- params/superchain.go
Change Ecotone activation time for Kroma mainnet.
The activation time is `Thu Apr 25 2024 08:00:01` (unix timestamp `1714032001`).
> chore: change Ecotone time for Kroma mainnet

- core/vm/logger.go
- eth/tracers/api_blocktrace.go
Since zkevm-circuits now supports Ecotone fee collection logic, this feature becomes redundant.
This should be merged after https://github.com/kroma-network/zkevm-circuits/pull/39 and https://github.com/kroma-network/kroma-prover/pull/25.
> Revert "feat: add overhead and l1feescalar proofs to trace (#94)"

- Dockerfile
- funding.json
This PR is for release `v0.5.4`.
> feat: merge dev into main

- core/blockchain.go
- core/kroma_migration.go
- core/state/statedb.go
- eth/backend.go
- eth/tracers/native/prestate.go
- migration/migrator.go
- migration/migrator_newstate.go
- migration/migrator_validate.go
This PR introduces a new approach to state migration by changing the mechanism used in `applyNewTransition`. Instead of relying on the Trace API to obtain the `stateDiff`, the process now utilizes data from `stateDB.Commit()`. This ensures more robust handling of state changes, not only those triggered by user-executed transactions, but also those occurring due to other factors outside the scope captured by the Trace API. For example, this includes cases such as EIP-4788 sys calls and failed deposit transactions in Geth, which may not be fully captured by the Trace API. As a result, the new approach effectively addresses these edge cases and improves overall system stability.
1. During `stateDB.Commit()`, `stateDiff` are recorded in a temporary space within rawdb on a per-block basis. The …
> feat: new state migration approach

- migration/migrator.go
There was a bug that the result of `eth_getProof` is not verified after MPT migration, and it turns out that the the hashing function when generating account proof at `eth_getProof` depended on `Zktrie` config, which was set to be `true` at `finalizeTransition`.
This PR fixes by adding a single line to make the option to be false after writing config to rawdb at `finalizeTransition`.
> fix: revise `eth_getProof` error by setting Zktrie to false

- core/state_transition.go
- core/types/fee_distribution.go
- core/types/rollup_cost.go
- params/protocol_params.go
This PR is to change L1Block and fee recipient addresses at MPT migration fork.
You can test this by spinning up a Kroma devnet as follows:
1. Checkout to [this branch](https://github.com/kroma-network/kroma/pull/393) at `kroma`.
2. Replace the docker image for L2 with `smstack15/geth:mpt-a61dbd0ba`(temp image for testing) at `docker-compose.yml`.
3. Set MPT migration time offset as `"l2GenesisKromaMPTTimeOffset": "0x4"` and spin up the devnet.
Note that the l1 fee will not be accrued in this devnet, since `L1Block` address is not yet changed so that the fee scalars are recognized as 0. The l1 fee part is tested locally and checked that l1 fee is normally accrued if L1Block address is not changed after mpt migration.
> feat: change predeploy contract addresses

- core/types/rollup_cost.go
- core/types/rollup_cost_test.go
Found an issue while testing at devnet, and this PR is fixing that issue.
While deriving receipt from block data, it uses `extractL1GasParamsEcotone` function, and it checks the length of calldata of L1Block transaction to be 196. However, after MPT migration, it will be shortened to 164, since `validatorRewardScalar` will be no longer included in the calldata. 
This was what I missed at #125, so I fixed the function to do separate checks with `isKromaMPT` boolean.
> fix: add check for data length of L1Block transaction after MPT migration

- core/block_validator.go
- core/blockchain_test.go
DepositTx must be of type `types.KromaDepositTx` before KromaMPT activation and of type `types.DepositTx` after KromaMPT activation. 
This is checked each time `insertChain()` is called, and an error is raised if an unexpected DepositTx type is encountered.
> feat(core): validate whether DepositTx is correct based on the time

- migration/migrator_validate.go
This PR resolves a memory leak issue in the migration validation logic.
**Problem**
When zktrie.Commit() is called, dirties are stored in memory within the ZktrieDatabase used by the trie. These dirties are not cleared unless the database is explicitly committed or dereferenced, leading to memory leaks.
Also, the preimageStore used in zktrie causes a memory leak because the zktDB is neither updated nor committed in validation.
**Solution**
1. The code has been updated to calculate the root hash without calling zktrie.Commit(). Instead, a function that computes the root hash directly is now used, preventing unnecessary memory usage.
2. The custom transformKey function has been used to ensure that keys are not added to the preimageStore during validation.
> fix(migration): fix memory leak issue in validation

- migration/migrator.go
Wait until first migration becomes possible.
For migration to be possible, the target block must become safe, and the state changes of the block following the target block must be stored in the database.
> feat(migration): wait until first migration becomes possible

- migration/migrator.go
This adds a bypass for hash collision check if `mptNode` is an empty hash. `mptNode` can be empty when it is deleted, and this can lead to an unexpected behavior if the value exists when we check the db with empty hash.
> fix(migration): skip the case of node deletion at hash collision check

- params/superchain.go
1735794000 (2025-01-02 5:00:00 AM UTC)
> chore: postpone devnet KromaMPT time

- core/kroma_migration.go
- migration/migrator.go
After the migration process is complete, delete any remaining temporary state changes data that might not have been removed.
> feat: delete all temporarily stored state changes for MPT migration

- core/kroma_migration.go
- migration/migrator.go
Due to an issue where deleting state change also deletes trie nodes, the functionality for deleting state change data has been removed.
To explain in more detail, there is a process that deletes all keys starting with the prefix `aC-`, which is used to record account changes. However, when converting the hash of a trie node to a string, some hashes happened to start with `aC-`. Deleting these keys caused a "missing trie node" error. To prevent this issue, the code for deleting state changes has been removed.
Related: #138
> fix: remove the functionality for deleting all state changes
